var path=require("path");
module.exports={
entry:"./src/temp.js",
output:{
path:path.join(__dirname,"public"),
filename:"bundle.js"
},
module:{
    rules:[{
loader:"babel-loader",
test:/\.js$/,
exclude:/nodemodules/
    },{
        test:/\.s?css$/,
        use:[
            "style-loader",
              "css-loader",
              "sass-loader"
        ]
    }
]
},
devtool:"cheap-module-eval-source-map",
devServer:{
    contentBase:path.join(__dirname,"public")
}
}